#! /bin/sh

# These commands are run inside Qemu after Qemu loads a version of the current
# directory into memory.

if [ -f labstuff.tgz ]; then
    tar -mxzf labstuff.tgz
    cd `tar -tzf labstuff.tgz | head -n 1`
    for i in `tar -tzf ../labstuff.tgz | sed 's/^[^\/]*\///;s/\/$//' | grep . | grep -v /`; do mv $i ..; done
    cd ..
fi

if [ -f setup-in-qemu2 ]; then
    ./setup-in-qemu2
fi

make clean
make || exit 1
echo
echo "*** ospfs.ko built successfully.  Now loading module."
insmod ospfs.ko
if [ ! -e test ]; then
    echo "*** Creating test directory."
    mkdir test
fi
echo "*** Mounting ospfs in the test directory."
/bin/mount -t ospfs none test || exit 1
echo "*** You may now test your filesystem by making changes to the test directory."
echo
